{% set name = "tangram_selection" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  url: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram

about:
  home: http://github.com/insilichem/tangram_selection
  license: MIT
  license_family: MIT

  summary: 'Experimental Tk widget to select items in UCSF Chimera a la Excel'

  description: |
    Experimental Tk widget to select items in UCSF Chimera a la Excel.
  doc_url: http://tangram-suite.readthedocs.io
  dev_url: https://github.com/insilichem/tangram_selection


